
server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9262
  cloud:
    gateway:
      routes:
        - id : ORDERSERVICE
          uri: lb://ORDERSERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: ORDERSERVICE
                fallbackuri: forward:/orderServiceFallBack
        - id: PRODUCTSERVICE
          uri: lb://PRODUCTSERVICE
          predicates:
              - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCTSERVICE
                fallbackuri: forward:/productServiceFallBack
        - id: PAYMENTSERVICE
          uri: lb://PAYMENTSERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: PAYMENTSERVICE
                fallbackuri: forward:/paymentServiceFallBack